
// #################################################################
//
//   This file generated by Google Spreadsheet, please don't edit.
//             Wed Sep 21 2016 17:50:02 GMT+0900 (JST)
//
// #################################################################


using UnityEngine;


namespace JsonDataParser {

	public partial class MasterDataParser {

		public static readonly string	Decrypt3DES_Key = "3209c1f42f2825122ce82b5b061803efbed0a29ac694b387";
		public static readonly string	Decrypt3DES_IV = "1cc18ee9fbd4db88";

		public Json_Stage[]		Stage { get; private set; }
		public Json_World[]		World { get; private set; }
		public Json_Probability[]		Probability { get; private set; }
		public Json_PlayerStatus		PlayerStatus { get; private set; }
		public Json_Gimmick[]		Gimmick { get; private set; }
		public Json_RadishData[]		RadishData { get; private set; }
		public Json_Tutorial[]		Tutorial { get; private set; }
		public Json_GameData		GameData { get; private set; }
		public Json_StageSelectData		StageSelectData { get; private set; }
		public Json_SystemData		SystemData { get; private set; }
		public Json_LocalNotificationData[]		LocalNotificationData { get; private set; }


		public partial class Json_Stage {
			public int		id { get; private set; }
			public int		worldId { get; private set; }
			public int		stageNum { get; private set; }
			public string		map { get; private set; }
			public string		rankingId { get; private set; }
			public int		probabilityId { get; private set; }
			public int		tutorialId { get; private set; }
		}

		public partial class Json_World {
			public int		id { get; private set; }
			public string		name { get; private set; }
			public string		tipid { get; private set; }
		}

		public partial class Json_Probability {
			public int		id { get; private set; }
			public int		p001 { get; private set; }
			public int		p002 { get; private set; }
			public int		p003 { get; private set; }
			public int		p004 { get; private set; }
			public int		p005 { get; private set; }
			public int		p006 { get; private set; }
			public int		p007 { get; private set; }
			public int		p008 { get; private set; }
			public int		p009 { get; private set; }
		}

		public partial class Json_PlayerStatus {
			public float		speed { get; private set; }
			public float		curve_wait_time { get; private set; }
			public float		pos_trans_interval { get; private set; }
			public float		time_invisible { get; private set; }
		}

		public partial class Json_Gimmick {
			public string		gimmickType { get; private set; }
			public int		param1 { get; private set; }
			public int		param2 { get; private set; }
			public int		param3 { get; private set; }
			public int		param4 { get; private set; }
			public int		param5 { get; private set; }
			public int		param6 { get; private set; }
		}

		public partial class Json_RadishData {
			public int		id { get; private set; }
			public int		unlock_worldId { get; private set; }
			public int		book_number { get; private set; }
			public string		name { get; private set; }
			public string		description { get; private set; }
			public string		hint { get; private set; }
			public int		id_appear_special { get; private set; }
			public string		start_appear_time { get; private set; }
			public string		end_appear_time { get; private set; }
			public int		probability_special { get; private set; }
		}

		public partial class Json_Tutorial {
			public int		id { get; private set; }
			public string		text1 { get; private set; }
			public string		image1 { get; private set; }
			public string		text2 { get; private set; }
			public string		image2 { get; private set; }
			public string		text3 { get; private set; }
			public string		image3 { get; private set; }
			public string		text4 { get; private set; }
			public string		image4 { get; private set; }
		}

		public partial class Json_GameData {
			public int		continue_quota { get; private set; }
			public int		continue_radish_rate { get; private set; }
			public int		skip_quota { get; private set; }
			public float		warp_complete_time { get; private set; }
			public float		continue_deadline { get; private set; }
			public float		duration_clear_time { get; private set; }
			public float		duration_clear_rank { get; private set; }
			public float		duration_result_radish { get; private set; }
			public float		add_alpha_of_frame { get; private set; }
			public float		add_alpha_of_frame_fast { get; private set; }
		}

		public partial class Json_StageSelectData {
			public int		review_quota { get; private set; }
		}

		public partial class Json_SystemData {
			public string		mail_address { get; private set; }
			public string		review_message { get; private set; }
			public string		thanks_message { get; private set; }
			public string		apology_message { get; private set; }
			public string		url_store_ios { get; private set; }
			public string		url_store_android { get; private set; }
			public string		text_tweet { get; private set; }
		}

		public partial class Json_LocalNotificationData {
			public string		date_interval { get; private set; }
			public string		notification_time1 { get; private set; }
			public string		notification_time2 { get; private set; }
			public string		notification_time3 { get; private set; }
			public string		title_text { get; private set; }
			public string		ticker_text1 { get; private set; }
			public string		ticker_text2 { get; private set; }
			public string		ticker_text3 { get; private set; }
			public string		android_only_text { get; private set; }
		}

	}

}
